import assert from 'node:assert/strict'
import test from 'node:test'
import shellExtension from './restrict-bash.ts'

type ToolCallHandler = (event: unknown, ctx?: unknown) => unknown | Promise<unknown>

test('blocks forbidden built-in tools', async () => {
  const handler = createToolCallHandler()
  const grepResult = await handler({ toolName: 'grep', input: { pattern: 'x', path: '.' } })
  assert(isBlocked(grepResult))
  assert.match(grepResult.reason, /The `grep` tool is blocked/)
  const lsResult = await handler({ toolName: 'ls', input: { path: '.' } })
  assert(isBlocked(lsResult))
  assert.match(lsResult.reason, /The `ls` tool is blocked/)
})

test('blocks bash tool calls without a command', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: {} })
  assert(isBlocked(result))
  assert.match(result.reason, /called without a command/)
})

test('blocks command substitution and variable expansion', async () => {
  const handler = createToolCallHandler()
  const backticks = await handler({ toolName: 'bash', input: { command: 'echo `date`' } })
  assert(isBlocked(backticks))
  assert.match(backticks.reason, /backticks/)
  const dollarParens = await handler({ toolName: 'bash', input: { command: 'echo $(date)' } })
  assert(isBlocked(dollarParens))
  assert.match(dollarParens.reason, /\$\(\)/)
  const variableExpansion = await handler({ toolName: 'bash', input: { command: 'echo $HOME' } })
  assert(isBlocked(variableExpansion))
  assert.match(variableExpansion.reason, /Variable expansion/)
})

test('blocks redirects, subshell syntax, and background execution', async () => {
  const handler = createToolCallHandler()
  const redirect = await handler({ toolName: 'bash', input: { command: 'echo hi > out.txt' } })
  assert(isBlocked(redirect))
  assert.match(redirect.reason, /Redirection/)
  const subshell = await handler({ toolName: 'bash', input: { command: '(echo hi)' } })
  assert(isBlocked(subshell))
  assert.match(subshell.reason, /Subshell/)
  const background = await handler({ toolName: 'bash', input: { command: 'sleep 1 &' } })
  assert(isBlocked(background))
  assert.match(background.reason, /Background execution/)
})

test('blocks unterminated quotes', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: 'echo "hi' } })
  assert(isBlocked(result))
  assert.match(result.reason, /Unterminated quotes/)
})

test('blocks wrapper and search/listing commands', async () => {
  const handler = createToolCallHandler()
  const wrapper = await handler({ toolName: 'bash', input: { command: 'eval echo hi' } })
  assert(isBlocked(wrapper))
  assert.match(wrapper.reason, /wrapper command is blocked/)
  const timeWrapper = await handler({ toolName: 'bash', input: { command: 'time npx cowsay hi' } })
  assert(isBlocked(timeWrapper))
  assert.match(timeWrapper.reason, /wrapper command is blocked/)
  const watchWrapper = await handler({ toolName: 'bash', input: { command: 'watch -n 1 npx cowsay hi' } })
  assert(isBlocked(watchWrapper))
  assert.match(watchWrapper.reason, /wrapper command is blocked/)
  const stdbufWrapper = await handler({ toolName: 'bash', input: { command: 'stdbuf -oL npx cowsay hi' } })
  assert(isBlocked(stdbufWrapper))
  assert.match(stdbufWrapper.reason, /wrapper command is blocked/)
  const listing = await handler({ toolName: 'bash', input: { command: 'command ls -la' } })
  assert(isBlocked(listing))
  assert.match(listing.reason, /search\/listing command is blocked/)
})

test('blocks command runners, scaffolding launchers, and ambiguous flagged forms', async () => {
  const handler = createToolCallHandler()
  const npxResult = await handler({ toolName: 'bash', input: { command: 'npx cowsay hi' } })
  assert(isBlocked(npxResult))
  assert.match(npxResult.reason, /command runner `npx` is blocked/)
  const uvxResult = await handler({ toolName: 'bash', input: { command: 'uvx ruff check .' } })
  assert(isBlocked(uvxResult))
  assert.match(uvxResult.reason, /command runner `uvx` is blocked/)
  const bunxResult = await handler({ toolName: 'bash', input: { command: 'bunx cowsay hi' } })
  assert(isBlocked(bunxResult))
  assert.match(bunxResult.reason, /command runner `bunx` is blocked/)
  const pnpxResult = await handler({ toolName: 'bash', input: { command: 'pnpx cowsay hi' } })
  assert(isBlocked(pnpxResult))
  assert.match(pnpxResult.reason, /command runner `pnpx` is blocked/)
  const pnpmDlxResult = await handler({ toolName: 'bash', input: { command: 'pnpm dlx cowsay hi' } })
  assert(isBlocked(pnpmDlxResult))
  assert.match(pnpmDlxResult.reason, /command runner `pnpm dlx` is blocked/)
  const pnpmDlxWithFlagResult = await handler({ toolName: 'bash', input: { command: 'pnpm --filter foo dlx cowsay hi' } })
  assert(isBlocked(pnpmDlxWithFlagResult))
  assert.match(pnpmDlxWithFlagResult.reason, /command runner `pnpm dlx` is blocked/)
  const yarnDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn dlx cowsay hi' } })
  assert(isBlocked(yarnDlxResult))
  assert.match(yarnDlxResult.reason, /command runner `yarn dlx` is blocked/)
  const yarnDlxWithFlagResult = await handler({ toolName: 'bash', input: { command: 'yarn --cwd . dlx cowsay hi' } })
  assert(isBlocked(yarnDlxWithFlagResult))
  assert.match(yarnDlxWithFlagResult.reason, /command runner `yarn dlx` is blocked/)
  const yarnWorkspaceDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn workspace my-app dlx cowsay hi' } })
  assert(isBlocked(yarnWorkspaceDlxResult))
  assert.match(yarnWorkspaceDlxResult.reason, /command runner `yarn dlx` is blocked/)
  const yarnWorkspacesForeachDlxResult = await handler({ toolName: 'bash', input: { command: 'yarn workspaces foreach dlx cowsay hi' } })
  assert(isBlocked(yarnWorkspacesForeachDlxResult))
  assert.match(yarnWorkspacesForeachDlxResult.reason, /command runner `yarn dlx` is blocked/)
  const npmExecResult = await handler({ toolName: 'bash', input: { command: 'npm exec cowsay hi' } })
  assert(isBlocked(npmExecResult))
  assert.match(npmExecResult.reason, /command runner `npm exec` is blocked/)
  const npmExecWithFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --prefix . exec cowsay hi' } })
  assert(isBlocked(npmExecWithFlagResult))
  assert.match(npmExecWithFlagResult.reason, /command runner `npm exec` is blocked/)
  const npmExecWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --cache /tmp exec cowsay hi' } })
  assert(isBlocked(npmExecWithUnknownValueFlagResult))
  assert.match(npmExecWithUnknownValueFlagResult.reason, /command runner `npm exec` is blocked/)
  const npmWorkspaceExecResult = await handler({ toolName: 'bash', input: { command: 'npm workspace my-app exec cowsay hi' } })
  assert(isBlocked(npmWorkspaceExecResult))
  assert.match(npmWorkspaceExecResult.reason, /command runner `npm exec` is blocked/)
  const npmWorkspacesExecResult = await handler({ toolName: 'bash', input: { command: 'npm workspaces exec cowsay hi' } })
  assert(isBlocked(npmWorkspacesExecResult))
  assert.match(npmWorkspacesExecResult.reason, /command runner `npm exec` is blocked/)
  const bunXResult = await handler({ toolName: 'bash', input: { command: 'bun x cowsay hi' } })
  assert(isBlocked(bunXResult))
  assert.match(bunXResult.reason, /command runner `bun x` is blocked/)
  const uvToolRunResult = await handler({ toolName: 'bash', input: { command: 'uv tool run ruff check .' } })
  assert(isBlocked(uvToolRunResult))
  assert.match(uvToolRunResult.reason, /command runner `uv tool run` is blocked/)
  const uvToolRunWithInterleavedFlagResult = await handler({ toolName: 'bash', input: { command: 'uv tool --verbose run ruff check .' } })
  assert(isBlocked(uvToolRunWithInterleavedFlagResult))
  assert.match(uvToolRunWithInterleavedFlagResult.reason, /command runner `uv tool run` is blocked/)
  const uvToolRunWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'uv --index-url https://example.com tool run ruff check .' } })
  assert(isBlocked(uvToolRunWithUnknownValueFlagResult))
  assert.match(uvToolRunWithUnknownValueFlagResult.reason, /command runner `uv tool run` is blocked/)
  const npmCreateResult = await handler({ toolName: 'bash', input: { command: 'npm create vite@latest app' } })
  assert(isBlocked(npmCreateResult))
  assert.match(npmCreateResult.reason, /command runner `npm create` is blocked/)
  const npmCreateWithUnknownValueFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --registry https://evil.com create vite@latest app' } })
  assert(isBlocked(npmCreateWithUnknownValueFlagResult))
  assert.match(npmCreateWithUnknownValueFlagResult.reason, /command runner `npm create` is blocked/)
  const npmCreateWithUserConfigFlagResult = await handler({ toolName: 'bash', input: { command: 'npm --userconfig ./my-conf create vite app' } })
  assert(isBlocked(npmCreateWithUserConfigFlagResult))
  assert.match(npmCreateWithUserConfigFlagResult.reason, /command runner `npm create` is blocked/)
  const npmInitResult = await handler({ toolName: 'bash', input: { command: 'npm init vite@latest app' } })
  assert(isBlocked(npmInitResult))
  assert.match(npmInitResult.reason, /command runner `npm init` is blocked/)
  const yarnCreateResult = await handler({ toolName: 'bash', input: { command: 'yarn create vite app' } })
  assert(isBlocked(yarnCreateResult))
  assert.match(yarnCreateResult.reason, /command runner `yarn create` is blocked/)
  const pnpmCreateResult = await handler({ toolName: 'bash', input: { command: 'pnpm create vite app' } })
  assert(isBlocked(pnpmCreateResult))
  assert.match(pnpmCreateResult.reason, /command runner `pnpm create` is blocked/)
  const bunCreateResult = await handler({ toolName: 'bash', input: { command: 'bun create vite app' } })
  assert(isBlocked(bunCreateResult))
  assert.match(bunCreateResult.reason, /command runner `bun create` is blocked/)
  const npmCreateAfterDashDashResult = await handler({ toolName: 'bash', input: { command: 'npm help -- create' } })
  assert.equal(npmCreateAfterDashDashResult, undefined)
  const pnpmExecResult = await handler({ toolName: 'bash', input: { command: 'pnpm exec cowsay hi' } })
  assert.equal(pnpmExecResult, undefined)
  const npmInstallExecPackageResult = await handler({ toolName: 'bash', input: { command: 'npm install exec' } })
  assert.equal(npmInstallExecPackageResult, undefined)
  const npmRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm run create' } })
  assert.equal(npmRunCreateScriptResult, undefined)
  const npmSilentRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm --silent run create' } })
  assert.equal(npmSilentRunCreateScriptResult, undefined)
  const npmCacheEqualsRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'npm --cache=/tmp run create' } })
  assert.equal(npmCacheEqualsRunCreateScriptResult, undefined)
  const yarnSilentRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'yarn --silent run create' } })
  assert.equal(yarnSilentRunCreateScriptResult, undefined)
  const yarnCwdEqualsRunCreateScriptResult = await handler({ toolName: 'bash', input: { command: 'yarn --cwd=. run create' } })
  assert.equal(yarnCwdEqualsRunCreateScriptResult, undefined)
  const npmSilentCreateResult = await handler({ toolName: 'bash', input: { command: 'npm --silent create vite@latest app' } })
  assert(isBlocked(npmSilentCreateResult))
  assert.match(npmSilentCreateResult.reason, /command runner `npm create` is blocked/)
  const yarnAddDlxPackageResult = await handler({ toolName: 'bash', input: { command: 'yarn add dlx' } })
  assert.equal(yarnAddDlxPackageResult, undefined)
})

test('allows run-script commands across package managers', async () => {
  const handler = createToolCallHandler()
  const npmRunBuildResult = await handler({ toolName: 'bash', input: { command: 'npm run build' } })
  assert.equal(npmRunBuildResult, undefined)
  const npmRunTestResult = await handler({ toolName: 'bash', input: { command: 'npm run test' } })
  assert.equal(npmRunTestResult, undefined)
  const yarnRunBuildResult = await handler({ toolName: 'bash', input: { command: 'yarn run build' } })
  assert.equal(yarnRunBuildResult, undefined)
  const yarnRunCreateResult = await handler({ toolName: 'bash', input: { command: 'yarn run create' } })
  assert.equal(yarnRunCreateResult, undefined)
  const yarnWorkspacesForeachRunBuildResult = await handler({ toolName: 'bash', input: { command: 'yarn workspaces foreach run build' } })
  assert.equal(yarnWorkspacesForeachRunBuildResult, undefined)
  const pnpmRunBuildResult = await handler({ toolName: 'bash', input: { command: 'pnpm run build' } })
  assert.equal(pnpmRunBuildResult, undefined)
  const pnpmRunCreateResult = await handler({ toolName: 'bash', input: { command: 'pnpm run create' } })
  assert.equal(pnpmRunCreateResult, undefined)
  const bunRunBuildResult = await handler({ toolName: 'bash', input: { command: 'bun run build' } })
  assert.equal(bunRunBuildResult, undefined)
  const bunRunCreateResult = await handler({ toolName: 'bash', input: { command: 'bun run create' } })
  assert.equal(bunRunCreateResult, undefined)
})

test('blocks path-qualified blocked commands', async () => {
  const handler = createToolCallHandler()
  const absoluteNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/local/bin/npx cowsay hi' } })
  assert(isBlocked(absoluteNpxResult))
  assert.match(absoluteNpxResult.reason, /command runner `npx` is blocked/)
  const pathQualifiedEnvNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/bin/env npx cowsay hi' } })
  assert(isBlocked(pathQualifiedEnvNpxResult))
  assert.match(pathQualifiedEnvNpxResult.reason, /command runner `npx` is blocked/)
  const pathQualifiedEnvWithFlagNpxResult = await handler({ toolName: 'bash', input: { command: '/usr/bin/env -i npx cowsay hi' } })
  assert(isBlocked(pathQualifiedEnvWithFlagNpxResult))
  assert.match(pathQualifiedEnvWithFlagNpxResult.reason, /command runner `npx` is blocked/)
  const pathQualifiedCommandLsResult = await handler({ toolName: 'bash', input: { command: '/bin/command ls -la' } })
  assert(isBlocked(pathQualifiedCommandLsResult))
  assert.match(pathQualifiedCommandLsResult.reason, /search\/listing command is blocked/)
  const relativeNpmCreateResult = await handler({ toolName: 'bash', input: { command: './node_modules/.bin/npm create vite@latest app' } })
  assert(isBlocked(relativeNpmCreateResult))
  assert.match(relativeNpmCreateResult.reason, /command runner `npm create` is blocked/)
  const absoluteLsResult = await handler({ toolName: 'bash', input: { command: '/bin/ls -la' } })
  assert(isBlocked(absoluteLsResult))
  assert.match(absoluteLsResult.reason, /search\/listing command is blocked/)
})

test('blocks sed in-place edits', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: "sed -i 's/a/b/' file.txt" } })
  assert(isBlocked(result))
  assert.match(result.reason, /sed -i/)
})

test('blocks git commands that can mutate the repo, allows safe reads', async () => {
  const handler = createToolCallHandler()
  const status = await handler({ toolName: 'bash', input: { command: 'git status' } })
  assert.equal(status, undefined)
  const commit = await handler({ toolName: 'bash', input: { command: 'git commit -m msg' } })
  assert(isBlocked(commit))
  assert.match(commit.reason, /git commit/)
  const commitWithGlobalFlag = await handler({ toolName: 'bash', input: { command: 'git -c foo=bar commit -m msg' } })
  assert(isBlocked(commitWithGlobalFlag))
  assert.match(commitWithGlobalFlag.reason, /git commit/)
  const statusWithCwdFlag = await handler({ toolName: 'bash', input: { command: 'git -C repo status' } })
  assert.equal(statusWithCwdFlag, undefined)
})

test('blocks shell control-flow keywords', async () => {
  const handler = createToolCallHandler()
  const result = await handler({ toolName: 'bash', input: { command: 'if true; then echo ok; fi' } })
  assert(isBlocked(result))
  assert.match(result.reason, /control-flow keyword/)
})

function createToolCallHandler(): ToolCallHandler {
  let toolCallHandler: ToolCallHandler | undefined
  const pi = {
    on: (eventName: string, handler: ToolCallHandler) => {
      if (eventName !== 'tool_call') return
      toolCallHandler = handler
    },
  }
  shellExtension(pi as never)
  assert(toolCallHandler)
  return toolCallHandler
}

function isBlocked(value: unknown): value is { block: true; reason: string } {
  if (!value || typeof value !== 'object') return false
  const candidate = value as { block?: unknown; reason?: unknown }
  return candidate.block === true && typeof candidate.reason === 'string'
}
